# all those glyphs will show as weird squares if you don't have the correct patched font
# My advice is to use NerdFonts which can be found here:
# https://github.com/ryanoasis/nerd-fonts

# Default fallback icons
[defaults]
file = "î˜’"
directory = "î—¿"

# Directory exact match icons
[directory_exact]
# English
".git" = "î—»"
"desktop" = "ï„ˆ"
"document" = "ï"
"download" = "ï’˜"
"dotfile" = "îœ‡"
"dropbox" = "îœ‡"
"music" = "ï€¥"
"picture" = "î‰„"
"public" = "ï«"
"template" = "ïƒ…"
"video" = "ï‘‡"
"alice" = "ó±‚µ"
"github" = "î¬€"
"fantasy" = "ó°½°"
"lwifew" = "î€€"
"ws" = "î¼Ÿ"
"book" = "îª¤"
"ebook" = "îª¤"
"mirror" = "ó±‡½"
"tmp" = "îª"
"private" = "î©¬"
"iMiku" = "ï±"
"Miku" = "ï±"
"imiku" = "ï±"
"miku" = "ï±"
"ant" = "ğŸª·"
"home" = "ó±‚µ"
"dev" = "î»´"
"etc" = "î—¼"
"env" = "îªˆ"
"resource" = "î«ª"
"resources" = "î«ª"
"static" = "î«ª"
"src" = "î©¨"
"tool" = "î­­"
"tools" = "ó°¦­"
"local" = "ó°’"
"locals" = "ó°’"
"linux" = "ï…¼"
"macos" = "îœ‘"
"windows" = "î˜ª"
"bin" = "î«¨"
"app" = "ï‚½"
"apps" = "ï‚½"

# File exact match icons
[file_exact]
".bash_aliases" = "î˜•"
".bash_history" = "î˜•"
".bash_logout" = "î˜•"
".bash_profile" = "î˜•"
".bashprofile" = "î˜•"
".bashrc" = "î˜•"
".dmrc" = "î˜•"
".DS_Store" = "î˜•"
".fasd" = "î˜•"
".fehbg" = "î‰„"
".gitattributes" = "î˜•"
".gitconfig" = "î˜•"
".gitignore" = "î˜•"
".gitlab-ci.yml" = "ïŠ–"
".gvimrc" = "î˜«"
".inputrc" = "î˜•"
".jack-settings" = "î˜•"
".mime.types" = "î˜•"
".ncmpcpp" = "ï€"
".nvidia-settings-rc" = "î˜•"
".pam_environment" = "î˜•"
".profile" = "î˜•"
".recently-used" = "î˜•"
".selected_editor" = "î˜•"
".vim" = "îŸ…"
".viminfo" = "îŸ…"
".vimrc" = "îŸ…"
".Xauthority" = "î˜•"
".Xdefaults" = "î˜•"
".xinitrc" = "î˜•"
".xinputrc" = "î˜•"
".Xresources" = "î˜•"
".zshrc" = "î˜•"
"_gvimrc" = "î˜«"
"_vimrc" = "î˜«"
"a.out" = "î•"
"authorized_keys" = "î˜Š"
"bspwmrc" = "î˜•"
"cmakelists.txt" = "î˜•"
"config" = "î˜•"
"config.ac" = "î˜¤"
"config.m4" = "î˜¤"
"config.mk" = "î˜¤"
"config.ru" = "î‘"
"configure" = "î•"
"docker-compose.yml" = "ïŒˆ"
"dockerfile" = "î°"
"Dockerfile" = "ïŒˆ"
"dropbox" = "îœ‡"
"exact-match-case-sensitive-1.txt" = "X1"
"exact-match-case-sensitive-2" = "X2"
"favicon.ico" = "î˜£"
"gemfile" = "î‘"
"gruntfile.coffee" = "î˜‘"
"gruntfile.js" = "î˜‘"
"gruntfile.ls" = "î˜‘"
"gulpfile.coffee" = "î˜"
"gulpfile.js" = "î˜"
"gulpfile.ls" = "î˜"
"ini" = "î˜•"
"known_hosts" = "î˜Š"
"ledger" = "ï…•"
"license" = "î˜Š"
"LICENSE" = "î˜Š"
"LICENSE.md" = "î˜Š"
"LICENSE.txt" = "î˜Š"
"Makefile" = "î˜•"
"makefile" = "î˜•"
"Makefile.ac" = "î˜•"
"Makefile.in" = "î˜•"
"mimeapps.list" = "î˜•"
"mix.lock" = "î˜­"
"node_modules" = "îœ˜"
"package-lock.json" = "îœ˜"
"package.json" = "îœ˜"
"playlists" = "ï€"
"procfile" = "î˜‡"
"Rakefile" = "î‘"
"rakefile" = "î‘"
"react.jsx" = "î˜¥"
"README" = "î˜‰"
"README.markdown" = "î˜‰"
"README.md" = "î˜‰"
"README.rst" = "î˜‰"
"README.txt" = "î˜‰"
"sxhkdrc" = "î˜•"
"user-dirs.dirs" = "î˜•"
"webpack.config.js" = "îœ˜"

# File extension match
[ext]
"3g2" = "ï€ˆ"
"3gp" = "ï€ˆ"
"7z" = "ï†‡"
"8svx" = "ï€"
"a" = "î˜¤"
"aa" = "ï€"
"aac" = "ï€"
"aax" = "ï€"
"ai" = "î´"
"aiff" = "ï€"
"alac" = "ï€"
"amr" = "ï€"
"amv" = "ï€ˆ"
"ape" = "ï€"
"apk" = "ï†‡"
"asf" = "ï€ˆ"
"asm" = "î˜”"
"asp" = "î•"
"au" = "ï€"
"aup" = "ï€"
"avi" = "ï€ˆ"
"awb" = "ï€"
"awk" = "î•"
"bash" = "î•"
"bat" = "î˜•"
"bmp" = "î˜"
"bz2" = "ï†‡"
"c" = "î˜"
"c++" = "î˜"
"cab" = "ï†‡"
"cbr" = "ïµ"
"cbz" = "ïµ"
"cc" = "î˜"
"cda" = "ï€"
"class" = "îœ¸"
"clj" = "î¨"
"cljc" = "î¨"
"cljs" = "îª"
"cmake" = "î˜¤"
"coffee" = "î˜›"
"conf" = "î˜•"
"cp" = "î˜"
"cpio" = "ï†‡"
"cpp" = "î˜"
"cs" = "ï š"
"csh" = "î•"
"css" = "î˜”"
"csv" = "î™Š"
"cue" = "ï€"
"cvs" = "î˜•"
"cxx" = "î˜"
"d" = "î¯"
"dart" = "î˜"
"db" = "îœ†"
"deb" = "ï†‡"
"diff" = "îœ¨"
"dll" = "îœ"
"doc" = "ï€­"
"docx" = "ï€­"
"dss" = "ï€"
"dump" = "îœ†"
"dvf" = "ï€"
"edn" = "îª"
"eex" = "î˜­"
"efi" = "î•"
"ejs" = "î˜"
"elf" = "î•"
"elm" = "î˜¬"
"epub" = "ï€­"
"erl" = "î±"
"ex" = "î˜­"
"exe" = "îœ"
"exs" = "î˜­"
"f//" = "î§"
"fifo" = "|"
"fish" = "î•"
"flac" = "ï€"
"flv" = "ï€ˆ"
"fs" = "î§"
"fsi" = "î§"
"fsscript" = "î§"
"fsx" = "î§"
"gem" = "ï†‡"
"gemspec" = "î‘"
"gif" = "î˜"
"gifv" = "î˜"
"go" = "î˜§"
"gsm" = "ï€"
"gz" = "ï†‡"
"gzip" = "ï†‡"
"h" = "î˜"
"haml" = "î˜"
"hbs" = "î˜"
"hh" = "ïƒ½"
"hpp" = "î˜"
"hrl" = "î±"
"hs" = "î˜Ÿ"
"htaccess" = "î˜•"
"htm" = "î˜"
"html" = "î˜"
"htpasswd" = "î˜•"
"hxx" = "ïƒ½"
"ico" = "î˜"
"iklax" = "ï€"
"img" = "îœ†"
"ini" = "î˜•"
"iso" = "îœ†"
"ivs" = "ï€"
"jar" = "îœ¸"
"java" = "îœ¸"
"jl" = "î˜¤"
"jpeg" = "î˜"
"jpg" = "î˜"
"js" = "î˜Œ"
"json" = "î˜‹"
"jsx" = "îº"
"key" = "î˜Š"
"ksh" = "î•"
"leex" = "î˜­"
"less" = "î˜”"
"lha" = "ï†‡"
"lhs" = "î˜Ÿ"
"log" = "ï‡ª"
"lua" = "î˜ "
"lzh" = "ï†‡"
"lzma" = "ï†‡"
"m4a" = "ï€"
"m4b" = "ï€"
"m4p" = "ï€"
"m4v" = "ï€ˆ"
"markdown" = "î˜‰"
"md" = "î˜‰"
"mdx" = "î˜‰"
"mjs" = "î˜Œ"
"mka" = "ï€"
"mkv" = "ï€ˆ"
"ml" = "Î»"
"mli" = "Î»"
"mmf" = "ï€"
"mng" = "ï€ˆ"
"mogg" = "ï€"
"mov" = "ï€ˆ"
"movpkg" = "ï€"
"mp3" = "ï€"
"mp4" = "ï€ˆ"
"mpc" = "ï€"
"mpeg" = "ï€ˆ"
"mpg" = "ï€ˆ"
"msi" = "îœ"
"msv" = "ï€"
"mustache" = "î˜"
"mxf" = "ï€ˆ"
"nix" = "ïŒ“"
"nmf" = "ï€"
"norg" = "î˜³"
"o" = "î˜¤"
"oga" = "ï€"
"ogg" = "ï€"
"opus" = "ï€"
"org" = "î˜³"
"pdf" = "ï€­"
"php" = "î˜ˆ"
"pl" = "î©"
"pm" = "î©"
"png" = "î˜"
"pp" = "ï’™"
"ppt" = "î˜"
"pptx" = "î˜"
"ps1" = "î•"
"psb" = "î¸"
"psd" = "î¸"
"pub" = "î˜Š"
"py" = "î˜†"
"pyc" = "î˜†"
"pyd" = "î˜†"
"pyo" = "î˜†"
"r" = "ï³’"
"ra" = "ï€"
"rake" = "î‘"
"rar" = "ï†‡"
"rb" = "î‘"
"rc" = "î˜•"
"rf64" = "ï€"
"rlib" = "î¨"
"rm" = "ï€ˆ"
"rmd" = "î˜‰"
"rmvb" = "ï€ˆ"
"rom" = "î•"
"rpm" = "ï†‡"
"rproj" = "ï«…"
"rs" = "î¨"
"rss" = "î˜™"
"rtf" = "ï€­"
"s" = "î˜”"
"sass" = "î˜ƒ"
"scala" = "îœ·"
"scss" = "î˜ƒ"
"sh" = "î˜”"
"slim" = "î˜"
"sln" = "îœŒ"
"so" = "î˜¤"
"sql" = "îœ†"
"styl" = "î˜€"
"suo" = "îœŒ"
"svi" = "ï€ˆ"
"swift" = "î•"
"t" = "î©"
"tar" = "ï†‡"
"tex" = "ï­¨"
"tgz" = "ï†‡"
"toml" = "î˜•"
"ts" = "î˜¨"
"tsx" = "îº"
"tta" = "ï€"
"twig" = "î˜œ"
"vim" = "îŸ…"
"vimrc" = "îŸ…"
"viv" = "ï€ˆ"
"vob" = "ï€ˆ"
"voc" = "ï€"
"vox" = "ï€"
"vue" = "ïµ‚"
"wav" = "ï€"
"wasm" = "îš¡"
"webm" = "ï€ˆ"
"webmanifest" = "î˜‹"
"webp" = "î˜"
"wma" = "ï€"
"wmv" = "ï€ˆ"
"wv" = "ï€"
"xbps" = "ï†‡"
"xcplayground" = "î•"
"xhtml" = "î˜"
"xls" = "ï€­"
"xlsx" = "ï€­"
"xml" = "î˜"
"xul" = "î…"
"xz" = "ï†‡"
"yaml" = "î˜•"
"yml" = "î˜•"
"yuv" = "ï€ˆ"
"zip" = "ï†‡"
"zsh" = "î•"
"lock" = "î©µ"
